[workspace]
members = [
    "rheia-client",
    "rheia-server",
    "rheia-common",
    "rheia-physics",
    "rheia-network",
    "rheia-network/examples/connection",
    "rheia-map-preview",
]
resolver = "2"
