block_types = [
    'Air',
    'Stone',
    'Granite',
    'PolishedGranite',
    'Diorite',
    'PolishedDiorite',
    'Andesite',
    'PolishedAndesite',
    'GrassBlock',
    'Dirt',
    'CoarseDirt',
    'Podzol',
    'Cobblestone',
    'OakPlanks',
    'SprucePlanks',
    'BirchPlanks',
    'JunglePlanks',
    'AcaciaPlanks',
    'DarkOakPlanks',
    'OakSapling',
    'SpruceSapling',
    'BirchSapling',
    'JungleSapling',
    'AcaciaSapling',
    'DarkOakSapling',
    'Bedrock',
    'Water',
    'Lava',
    'Sand',
    'RedSand',
    'Gravel',
    'GoldOre',
    'IronOre',
    'CoalOre',
    'NetherGoldOre',
    'OakLog',
    'SpruceLog',
    'BirchLog',
    'JungleLog',
    'AcaciaLog',
    'DarkOakLog',
    'StrippedSpruceLog',
    'StrippedBirchLog',
    'StrippedJungleLog',
    'StrippedAcaciaLog',
    'StrippedDarkOakLog',
    'StrippedOakLog',
    'OakWood',
    'SpruceWood',
    'BirchWood',
    'JungleWood',
    'AcaciaWood',
    'DarkOakWood',
    'StrippedOakWood',
    'StrippedSpruceWood',
    'StrippedBirchWood',
    'StrippedJungleWood',
    'StrippedAcaciaWood',
    'StrippedDarkOakWood',
    'OakLeaves',
    'SpruceLeaves',
    'BirchLeaves',
    'JungleLeaves',
    'AcaciaLeaves',
    'DarkOakLeaves',
    'Sponge',
    'WetSponge',
    'Glass',
    'LapisOre',
    'LapisBlock',
    'Dispenser',
    'Sandstone',
    'ChiseledSandstone',
    'CutSandstone',
    'NoteBlock',
    'WhiteBed',
    'OrangeBed',
    'MagentaBed',
    'LightBlueBed',
    'YellowBed',
    'LimeBed',
    'PinkBed',
    'GrayBed',
    'LightGrayBed',
    'CyanBed',
    'PurpleBed',
    'BlueBed',
    'BrownBed',
    'GreenBed',
    'RedBed',
    'BlackBed',
    'PoweredRail',
    'DetectorRail',
    'StickyPiston',
    'Cobweb',
    'Grass',
    'Fern',
    'DeadBush',
    'Seagrass',
    'TallSeagrass',
    'Piston',
    'PistonHead',
    'WhiteWool',
    'OrangeWool',
    'MagentaWool',
    'LightBlueWool',
    'YellowWool',
    'LimeWool',
    'PinkWool',
    'GrayWool',
    'LightGrayWool',
    'CyanWool',
    'PurpleWool',
    'BlueWool',
    'BrownWool',
    'GreenWool',
    'RedWool',
    'BlackWool',
    'MovingPiston',
    'Dandelion',
    'Poppy',
    'BlueOrchid',
    'Allium',
    'AzureBluet',
    'RedTulip',
    'OrangeTulip',
    'WhiteTulip',
    'PinkTulip',
    'OxeyeDaisy',
    'Cornflower',
    'WitherRose',
    'LilyOfTheValley',
    'BrownMushroom',
    'RedMushroom',
    'GoldBlock',
    'IronBlock',
    'Bricks',
    'Tnt',
    'Bookshelf',
    'MossyCobblestone',
    'Obsidian',
    'Torch',
    'WallTorch',
    'Fire',
    'SoulFire',
    'Spawner',
    'OakStairs',
    'Chest',
    'RedstoneWire',
    'DiamondOre',
    'DiamondBlock',
    'CraftingTable',
    'Wheat',
    'Farmland',
    'Furnace',
    'OakSign',
    'SpruceSign',
    'BirchSign',
    'AcaciaSign',
    'JungleSign',
    'DarkOakSign',
    'OakDoor',
    'Ladder',
    'Rail',
    'CobblestoneStairs',
    'OakWallSign',
    'SpruceWallSign',
    'BirchWallSign',
    'AcaciaWallSign',
    'JungleWallSign',
    'DarkOakWallSign',
    'Lever',
    'StonePressurePlate',
    'IronDoor',
    'OakPressurePlate',
    'SprucePressurePlate',
    'BirchPressurePlate',
    'JunglePressurePlate',
    'AcaciaPressurePlate',
    'DarkOakPressurePlate',
    'RedstoneOre',
    'RedstoneTorch',
    'RedstoneWallTorch',
    'StoneButton',
    'Snow',
    'Ice',
    'SnowBlock',
    'Cactus',
    'Clay',
    'SugarCane',
    'Jukebox',
    'OakFence',
    'Pumpkin',
    'Netherrack',
    'SoulSand',
    'SoulSoil',
    'Basalt',
    'PolishedBasalt',
    'SoulTorch',
    'SoulWallTorch',
    'Glowstone',
    'NetherPortal',
    'CarvedPumpkin',
    'JackOLantern',
    'Cake',
    'Repeater',
    'WhiteStainedGlass',
    'OrangeStainedGlass',
    'MagentaStainedGlass',
    'LightBlueStainedGlass',
    'YellowStainedGlass',
    'LimeStainedGlass',
    'PinkStainedGlass',
    'GrayStainedGlass',
    'LightGrayStainedGlass',
    'CyanStainedGlass',
    'PurpleStainedGlass',
    'BlueStainedGlass',
    'BrownStainedGlass',
    'GreenStainedGlass',
    'RedStainedGlass',
    'BlackStainedGlass',
    'OakTrapdoor',
    'SpruceTrapdoor',
    'BirchTrapdoor',
    'JungleTrapdoor',
    'AcaciaTrapdoor',
    'DarkOakTrapdoor',
    'StoneBricks',
    'MossyStoneBricks',
    'CrackedStoneBricks',
    'ChiseledStoneBricks',
    'InfestedStone',
    'InfestedCobblestone',
    'InfestedStoneBricks',
    'InfestedMossyStoneBricks',
    'InfestedCrackedStoneBricks',
    'InfestedChiseledStoneBricks',
    'BrownMushroomBlock',
    'RedMushroomBlock',
    'MushroomStem',
    'IronBars',
    'Chain',
    'GlassPane',
    'Melon',
    'AttachedPumpkinStem',
    'AttachedMelonStem',
    'PumpkinStem',
    'MelonStem',
    'Vine',
    'OakFenceGate',
    'BrickStairs',
    'StoneBrickStairs',
    'Mycelium',
    'LilyPad',
    'NetherBricks',
    'NetherBrickFence',
    'NetherBrickStairs',
    'NetherWart',
    'EnchantingTable',
    'BrewingStand',
    'Cauldron',
    'EndPortal',
    'EndPortalFrame',
    'EndStone',
    'DragonEgg',
    'RedstoneLamp',
    'Cocoa',
    'SandstoneStairs',
    'EmeraldOre',
    'EnderChest',
    'TripwireHook',
    'Tripwire',
    'EmeraldBlock',
    'SpruceStairs',
    'BirchStairs',
    'JungleStairs',
    'CommandBlock',
    'Beacon',
    'CobblestoneWall',
    'MossyCobblestoneWall',
    'FlowerPot',
    'PottedOakSapling',
    'PottedSpruceSapling',
    'PottedBirchSapling',
    'PottedJungleSapling',
    'PottedAcaciaSapling',
    'PottedDarkOakSapling',
    'PottedFern',
    'PottedDandelion',
    'PottedPoppy',
    'PottedBlueOrchid',
    'PottedAllium',
    'PottedAzureBluet',
    'PottedRedTulip',
    'PottedOrangeTulip',
    'PottedWhiteTulip',
    'PottedPinkTulip',
    'PottedOxeyeDaisy',
    'PottedCornflower',
    'PottedLilyOfTheValley',
    'PottedWitherRose',
    'PottedRedMushroom',
    'PottedBrownMushroom',
    'PottedDeadBush',
    'PottedCactus',
    'Carrots',
    'Potatoes',
    'OakButton',
    'SpruceButton',
    'BirchButton',
    'JungleButton',
    'AcaciaButton',
    'DarkOakButton',
    'SkeletonSkull',
    'SkeletonWallSkull',
    'WitherSkeletonSkull',
    'WitherSkeletonWallSkull',
    'ZombieHead',
    'ZombieWallHead',
    'PlayerHead',
    'PlayerWallHead',
    'CreeperHead',
    'CreeperWallHead',
    'DragonHead',
    'DragonWallHead',
    'Anvil',
    'ChippedAnvil',
    'DamagedAnvil',
    'TrappedChest',
    'LightWeightedPressurePlate',
    'HeavyWeightedPressurePlate',
    'Comparator',
    'DaylightDetector',
    'RedstoneBlock',
    'NetherQuartzOre',
    'Hopper',
    'QuartzBlock',
    'ChiseledQuartzBlock',
    'QuartzPillar',
    'QuartzStairs',
    'ActivatorRail',
    'Dropper',
    'WhiteTerracotta',
    'OrangeTerracotta',
    'MagentaTerracotta',
    'LightBlueTerracotta',
    'YellowTerracotta',
    'LimeTerracotta',
    'PinkTerracotta',
    'GrayTerracotta',
    'LightGrayTerracotta',
    'CyanTerracotta',
    'PurpleTerracotta',
    'BlueTerracotta',
    'BrownTerracotta',
    'GreenTerracotta',
    'RedTerracotta',
    'BlackTerracotta',
    'WhiteStainedGlassPane',
    'OrangeStainedGlassPane',
    'MagentaStainedGlassPane',
    'LightBlueStainedGlassPane',
    'YellowStainedGlassPane',
    'LimeStainedGlassPane',
    'PinkStainedGlassPane',
    'GrayStainedGlassPane',
    'LightGrayStainedGlassPane',
    'CyanStainedGlassPane',
    'PurpleStainedGlassPane',
    'BlueStainedGlassPane',
    'BrownStainedGlassPane',
    'GreenStainedGlassPane',
    'RedStainedGlassPane',
    'BlackStainedGlassPane',
    'AcaciaStairs',
    'DarkOakStairs',
    'SlimeBlock',
    'Barrier',
    'IronTrapdoor',
    'Prismarine',
    'PrismarineBricks',
    'DarkPrismarine',
    'PrismarineStairs',
    'PrismarineBrickStairs',
    'DarkPrismarineStairs',
    'PrismarineSlab',
    'PrismarineBrickSlab',
    'DarkPrismarineSlab',
    'SeaLantern',
    'HayBlock',
    'WhiteCarpet',
    'OrangeCarpet',
    'MagentaCarpet',
    'LightBlueCarpet',
    'YellowCarpet',
    'LimeCarpet',
    'PinkCarpet',
    'GrayCarpet',
    'LightGrayCarpet',
    'CyanCarpet',
    'PurpleCarpet',
    'BlueCarpet',
    'BrownCarpet',
    'GreenCarpet',
    'RedCarpet',
    'BlackCarpet',
    'Terracotta',
    'CoalBlock',
    'PackedIce',
    'Sunflower',
    'Lilac',
    'RoseBush',
    'Peony',
    'TallGrass',
    'LargeFern',
    'WhiteBanner',
    'OrangeBanner',
    'MagentaBanner',
    'LightBlueBanner',
    'YellowBanner',
    'LimeBanner',
    'PinkBanner',
    'GrayBanner',
    'LightGrayBanner',
    'CyanBanner',
    'PurpleBanner',
    'BlueBanner',
    'BrownBanner',
    'GreenBanner',
    'RedBanner',
    'BlackBanner',
    'WhiteWallBanner',
    'OrangeWallBanner',
    'MagentaWallBanner',
    'LightBlueWallBanner',
    'YellowWallBanner',
    'LimeWallBanner',
    'PinkWallBanner',
    'GrayWallBanner',
    'LightGrayWallBanner',
    'CyanWallBanner',
    'PurpleWallBanner',
    'BlueWallBanner',
    'BrownWallBanner',
    'GreenWallBanner',
    'RedWallBanner',
    'BlackWallBanner',
    'RedSandstone',
    'ChiseledRedSandstone',
    'CutRedSandstone',
    'RedSandstoneStairs',
    'OakSlab',
    'SpruceSlab',
    'BirchSlab',
    'JungleSlab',
    'AcaciaSlab',
    'DarkOakSlab',
    'StoneSlab',
    'SmoothStoneSlab',
    'SandstoneSlab',
    'CutSandstoneSlab',
    'PetrifiedOakSlab',
    'CobblestoneSlab',
    'BrickSlab',
    'StoneBrickSlab',
    'NetherBrickSlab',
    'QuartzSlab',
    'RedSandstoneSlab',
    'CutRedSandstoneSlab',
    'PurpurSlab',
    'SmoothStone',
    'SmoothSandstone',
    'SmoothQuartz',
    'SmoothRedSandstone',
    'SpruceFenceGate',
    'BirchFenceGate',
    'JungleFenceGate',
    'AcaciaFenceGate',
    'DarkOakFenceGate',
    'SpruceFence',
    'BirchFence',
    'JungleFence',
    'AcaciaFence',
    'DarkOakFence',
    'SpruceDoor',
    'BirchDoor',
    'JungleDoor',
    'AcaciaDoor',
    'DarkOakDoor',
    'EndRod',
    'ChorusPlant',
    'ChorusFlower',
    'PurpurBlock',
    'PurpurPillar',
    'PurpurStairs',
    'EndStoneBricks',
    'Beetroots',
    'GrassPath',
    'EndGateway',
    'RepeatingCommandBlock',
    'ChainCommandBlock',
    'FrostedIce',
    'MagmaBlock',
    'NetherWartBlock',
    'RedNetherBricks',
    'BoneBlock',
    'StructureVoid',
    'Observer',
    'ShulkerBox',
    'WhiteShulkerBox',
    'OrangeShulkerBox',
    'MagentaShulkerBox',
    'LightBlueShulkerBox',
    'YellowShulkerBox',
    'LimeShulkerBox',
    'PinkShulkerBox',
    'GrayShulkerBox',
    'LightGrayShulkerBox',
    'CyanShulkerBox',
    'PurpleShulkerBox',
    'BlueShulkerBox',
    'BrownShulkerBox',
    'GreenShulkerBox',
    'RedShulkerBox',
    'BlackShulkerBox',
    'WhiteGlazedTerracotta',
    'OrangeGlazedTerracotta',
    'MagentaGlazedTerracotta',
    'LightBlueGlazedTerracotta',
    'YellowGlazedTerracotta',
    'LimeGlazedTerracotta',
    'PinkGlazedTerracotta',
    'GrayGlazedTerracotta',
    'LightGrayGlazedTerracotta',
    'CyanGlazedTerracotta',
    'PurpleGlazedTerracotta',
    'BlueGlazedTerracotta',
    'BrownGlazedTerracotta',
    'GreenGlazedTerracotta',
    'RedGlazedTerracotta',
    'BlackGlazedTerracotta',
    'WhiteConcrete',
    'OrangeConcrete',
    'MagentaConcrete',
    'LightBlueConcrete',
    'YellowConcrete',
    'LimeConcrete',
    'PinkConcrete',
    'GrayConcrete',
    'LightGrayConcrete',
    'CyanConcrete',
    'PurpleConcrete',
    'BlueConcrete',
    'BrownConcrete',
    'GreenConcrete',
    'RedConcrete',
    'BlackConcrete',
    'WhiteConcretePowder',
    'OrangeConcretePowder',
    'MagentaConcretePowder',
    'LightBlueConcretePowder',
    'YellowConcretePowder',
    'LimeConcretePowder',
    'PinkConcretePowder',
    'GrayConcretePowder',
    'LightGrayConcretePowder',
    'CyanConcretePowder',
    'PurpleConcretePowder',
    'BlueConcretePowder',
    'BrownConcretePowder',
    'GreenConcretePowder',
    'RedConcretePowder',
    'BlackConcretePowder',
    'Kelp',
    'KelpPlant',
    'DriedKelpBlock',
    'TurtleEgg',
    'DeadTubeCoralBlock',
    'DeadBrainCoralBlock',
    'DeadBubbleCoralBlock',
    'DeadFireCoralBlock',
    'DeadHornCoralBlock',
    'TubeCoralBlock',
    'BrainCoralBlock',
    'BubbleCoralBlock',
    'FireCoralBlock',
    'HornCoralBlock',
    'DeadTubeCoral',
    'DeadBrainCoral',
    'DeadBubbleCoral',
    'DeadFireCoral',
    'DeadHornCoral',
    'TubeCoral',
    'BrainCoral',
    'BubbleCoral',
    'FireCoral',
    'HornCoral',
    'DeadTubeCoralFan',
    'DeadBrainCoralFan',
    'DeadBubbleCoralFan',
    'DeadFireCoralFan',
    'DeadHornCoralFan',
    'TubeCoralFan',
    'BrainCoralFan',
    'BubbleCoralFan',
    'FireCoralFan',
    'HornCoralFan',
    'DeadTubeCoralWallFan',
    'DeadBrainCoralWallFan',
    'DeadBubbleCoralWallFan',
    'DeadFireCoralWallFan',
    'DeadHornCoralWallFan',
    'TubeCoralWallFan',
    'BrainCoralWallFan',
    'BubbleCoralWallFan',
    'FireCoralWallFan',
    'HornCoralWallFan',
    'SeaPickle',
    'BlueIce',
    'Conduit',
    'BambooSapling',
    'Bamboo',
    'PottedBamboo',
    'VoidAir',
    'CaveAir',
    'BubbleColumn',
    'PolishedGraniteStairs',
    'SmoothRedSandstoneStairs',
    'MossyStoneBrickStairs',
    'PolishedDioriteStairs',
    'MossyCobblestoneStairs',
    'EndStoneBrickStairs',
    'StoneStairs',
    'SmoothSandstoneStairs',
    'SmoothQuartzStairs',
    'GraniteStairs',
    'AndesiteStairs',
    'RedNetherBrickStairs',
    'PolishedAndesiteStairs',
    'DioriteStairs',
    'PolishedGraniteSlab',
    'SmoothRedSandstoneSlab',
    'MossyStoneBrickSlab',
    'PolishedDioriteSlab',
    'MossyCobblestoneSlab',
    'EndStoneBrickSlab',
    'SmoothSandstoneSlab',
    'SmoothQuartzSlab',
    'GraniteSlab',
    'AndesiteSlab',
    'RedNetherBrickSlab',
    'PolishedAndesiteSlab',
    'DioriteSlab',
    'BrickWall',
    'PrismarineWall',
    'RedSandstoneWall',
    'MossyStoneBrickWall',
    'GraniteWall',
    'StoneBrickWall',
    'NetherBrickWall',
    'AndesiteWall',
    'RedNetherBrickWall',
    'SandstoneWall',
    'EndStoneBrickWall',
    'DioriteWall',
    'Scaffolding',
    'Loom',
    'Barrel',
    'Smoker',
    'BlastFurnace',
    'CartographyTable',
    'FletchingTable',
    'Grindstone',
    'Lectern',
    'SmithingTable',
    'Stonecutter',
    'Bell',
    'Lantern',
    'SoulLantern',
    'Campfire',
    'SoulCampfire',
    'SweetBerryBush',
    'WarpedStem',
    'StrippedWarpedStem',
    'WarpedHyphae',
    'StrippedWarpedHyphae',
    'WarpedNylium',
    'WarpedFungus',
    'WarpedWartBlock',
    'WarpedRoots',
    'NetherSprouts',
    'CrimsonStem',
    'StrippedCrimsonStem',
    'CrimsonHyphae',
    'StrippedCrimsonHyphae',
    'CrimsonNylium',
    'CrimsonFungus',
    'Shroomlight',
    'WeepingVines',
    'WeepingVinesPlant',
    'TwistingVines',
    'TwistingVinesPlant',
    'CrimsonRoots',
    'CrimsonPlanks',
    'WarpedPlanks',
    'CrimsonSlab',
    'WarpedSlab',
    'CrimsonPressurePlate',
    'WarpedPressurePlate',
    'CrimsonFence',
    'WarpedFence',
    'CrimsonTrapdoor',
    'WarpedTrapdoor',
    'CrimsonFenceGate',
    'WarpedFenceGate',
    'CrimsonStairs',
    'WarpedStairs',
    'CrimsonButton',
    'WarpedButton',
    'CrimsonDoor',
    'WarpedDoor',
    'CrimsonSign',
    'WarpedSign',
    'CrimsonWallSign',
    'WarpedWallSign',
    'StructureBlock',
    'Jigsaw',
    'Composter',
    'Target',
    'BeeNest',
    'Beehive',
    'HoneyBlock',
    'HoneycombBlock',
    'NetheriteBlock',
    'AncientDebris',
    'CryingObsidian',
    'RespawnAnchor',
    'PottedCrimsonFungus',
    'PottedWarpedFungus',
    'PottedCrimsonRoots',
    'PottedWarpedRoots',
    'Lodestone',
    'Blackstone',
    'BlackstoneStairs',
    'BlackstoneWall',
    'BlackstoneSlab',
    'PolishedBlackstone',
    'PolishedBlackstoneBricks',
    'CrackedPolishedBlackstoneBricks',
    'ChiseledPolishedBlackstone',
    'PolishedBlackstoneBrickSlab',
    'PolishedBlackstoneBrickStairs',
    'PolishedBlackstoneBrickWall',
    'GildedBlackstone',
    'PolishedBlackstoneStairs',
    'PolishedBlackstoneSlab',
    'PolishedBlackstonePressurePlate',
    'PolishedBlackstoneButton',
    'PolishedBlackstoneWall',
    'ChiseledNetherBricks',
    'CrackedNetherBricks',
    'QuartzBricks',
]

solid = {
    'Air': False,
    'Stone': True,
    'Granite': True,
    'PolishedGranite': True,
    'Diorite': True,
    'PolishedDiorite': True,
    'Andesite': True,
    'PolishedAndesite': True,
    'GrassBlock': True,
    'Dirt': True,
    'CoarseDirt': True,
    'Podzol': True,
    'Cobblestone': True,
    'OakPlanks': True,
    'SprucePlanks': True,
    'BirchPlanks': True,
    'JunglePlanks': True,
    'AcaciaPlanks': True,
    'DarkOakPlanks': True,
    'OakSapling': False,
    'SpruceSapling': False,
    'BirchSapling': False,
    'JungleSapling': False,
    'AcaciaSapling': False,
    'DarkOakSapling': False,
    'Bedrock': True,
    'Water': False,
    'Lava': False,
    'Sand': True,
    'RedSand': True,
    'Gravel': True,
    'GoldOre': True,
    'IronOre': True,
    'CoalOre': True,
    'NetherGoldOre': True,
    'OakLog': True,
    'SpruceLog': True,
    'BirchLog': True,
    'JungleLog': True,
    'AcaciaLog': True,
    'DarkOakLog': True,
    'StrippedSpruceLog': True,
    'StrippedBirchLog': True,
    'StrippedJungleLog': True,
    'StrippedAcaciaLog': True,
    'StrippedDarkOakLog': True,
    'StrippedOakLog': True,
    'OakWood': True,
    'SpruceWood': True,
    'BirchWood': True,
    'JungleWood': True,
    'AcaciaWood': True,
    'DarkOakWood': True,
    'StrippedOakWood': True,
    'StrippedSpruceWood': True,
    'StrippedBirchWood': True,
    'StrippedJungleWood': True,
    'StrippedAcaciaWood': True,
    'StrippedDarkOakWood': True,
    'OakLeaves': True,
    'SpruceLeaves': True,
    'BirchLeaves': True,
    'JungleLeaves': True,
    'AcaciaLeaves': True,
    'DarkOakLeaves': True,
    'Sponge': True,
    'WetSponge': True,
    'Glass': True,
    'LapisOre': True,
    'LapisBlock': True,
    'Dispenser': True,
    'Sandstone': True,
    'ChiseledSandstone': True,
    'CutSandstone': True,
    'NoteBlock': True,
    'WhiteBed': True,
    'OrangeBed': True,
    'MagentaBed': True,
    'LightBlueBed': True,
    'YellowBed': True,
    'LimeBed': True,
    'PinkBed': True,
    'GrayBed': True,
    'LightGrayBed': True,
    'CyanBed': True,
    'PurpleBed': True,
    'BlueBed': True,
    'BrownBed': True,
    'GreenBed': True,
    'RedBed': True,
    'BlackBed': True,
    'PoweredRail': False,
    'DetectorRail': False,
    'StickyPiston': True,
    'Cobweb': False,
    'Grass': False,
    'Fern': False,
    'DeadBush': False,
    'Seagrass': False,
    'TallSeagrass': False,
    'Piston': True,
    'PistonHead': True,
    'WhiteWool': True,
    'OrangeWool': True,
    'MagentaWool': True,
    'LightBlueWool': True,
    'YellowWool': True,
    'LimeWool': True,
    'PinkWool': True,
    'GrayWool': True,
    'LightGrayWool': True,
    'CyanWool': True,
    'PurpleWool': True,
    'BlueWool': True,
    'BrownWool': True,
    'GreenWool': True,
    'RedWool': True,
    'BlackWool': True,
    'MovingPiston': False,
    'Dandelion': False,
    'Poppy': False,
    'BlueOrchid': False,
    'Allium': False,
    'AzureBluet': False,
    'RedTulip': False,
    'OrangeTulip': False,
    'WhiteTulip': False,
    'PinkTulip': False,
    'OxeyeDaisy': False,
    'Cornflower': False,
    'WitherRose': False,
    'LilyOfTheValley': False,
    'BrownMushroom': False,
    'RedMushroom': False,
    'GoldBlock': True,
    'IronBlock': True,
    'Bricks': True,
    'Tnt': True,
    'Bookshelf': True,
    'MossyCobblestone': True,
    'Obsidian': True,
    'Torch': False,
    'WallTorch': False,
    'Fire': False,
    'SoulFire': False,
    'Spawner': True,
    'OakStairs': True,
    'Chest': True,
    'RedstoneWire': False,
    'DiamondOre': True,
    'DiamondBlock': True,
    'CraftingTable': True,
    'Wheat': False,
    'Farmland': True,
    'Furnace': True,
    'OakSign': False,
    'SpruceSign': False,
    'BirchSign': False,
    'AcaciaSign': False,
    'JungleSign': False,
    'DarkOakSign': False,
    'OakDoor': True,
    'Ladder': True,
    'Rail': False,
    'CobblestoneStairs': True,
    'OakWallSign': False,
    'SpruceWallSign': False,
    'BirchWallSign': False,
    'AcaciaWallSign': False,
    'JungleWallSign': False,
    'DarkOakWallSign': False,
    'Lever': False,
    'StonePressurePlate': False,
    'IronDoor': True,
    'OakPressurePlate': False,
    'SprucePressurePlate': False,
    'BirchPressurePlate': False,
    'JunglePressurePlate': False,
    'AcaciaPressurePlate': False,
    'DarkOakPressurePlate': False,
    'RedstoneOre': True,
    'RedstoneTorch': False,
    'RedstoneWallTorch': False,
    'StoneButton': False,
    'Snow': True,
    'Ice': True,
    'SnowBlock': True,
    'Cactus': True,
    'Clay': True,
    'SugarCane': False,
    'Jukebox': True,
    'OakFence': True,
    'Pumpkin': True,
    'Netherrack': True,
    'SoulSand': True,
    'SoulSoil': True,
    'Basalt': True,
    'PolishedBasalt': True,
    'SoulTorch': False,
    'SoulWallTorch': False,
    'Glowstone': True,
    'NetherPortal': False,
    'CarvedPumpkin': True,
    'JackOLantern': True,
    'Cake': True,
    'Repeater': True,
    'WhiteStainedGlass': True,
    'OrangeStainedGlass': True,
    'MagentaStainedGlass': True,
    'LightBlueStainedGlass': True,
    'YellowStainedGlass': True,
    'LimeStainedGlass': True,
    'PinkStainedGlass': True,
    'GrayStainedGlass': True,
    'LightGrayStainedGlass': True,
    'CyanStainedGlass': True,
    'PurpleStainedGlass': True,
    'BlueStainedGlass': True,
    'BrownStainedGlass': True,
    'GreenStainedGlass': True,
    'RedStainedGlass': True,
    'BlackStainedGlass': True,
    'OakTrapdoor': True,
    'SpruceTrapdoor': True,
    'BirchTrapdoor': True,
    'JungleTrapdoor': True,
    'AcaciaTrapdoor': True,
    'DarkOakTrapdoor': True,
    'StoneBricks': True,
    'MossyStoneBricks': True,
    'CrackedStoneBricks': True,
    'ChiseledStoneBricks': True,
    'InfestedStone': True,
    'InfestedCobblestone': True,
    'InfestedStoneBricks': True,
    'InfestedMossyStoneBricks': True,
    'InfestedCrackedStoneBricks': True,
    'InfestedChiseledStoneBricks': True,
    'BrownMushroomBlock': True,
    'RedMushroomBlock': True,
    'MushroomStem': True,
    'IronBars': True,
    'Chain': True,
    'GlassPane': True,
    'Melon': True,
    'AttachedPumpkinStem': False,
    'AttachedMelonStem': False,
    'PumpkinStem': False,
    'MelonStem': False,
    'Vine': False,
    'OakFenceGate': True,
    'BrickStairs': True,
    'StoneBrickStairs': True,
    'Mycelium': True,
    'LilyPad': True,
    'NetherBricks': True,
    'NetherBrickFence': True,
    'NetherBrickStairs': True,
    'NetherWart': False,
    'EnchantingTable': True,
    'BrewingStand': True,
    'Cauldron': True,
    'EndPortal': False,
    'EndPortalFrame': True,
    'EndStone': True,
    'DragonEgg': True,
    'RedstoneLamp': True,
    'Cocoa': True,
    'SandstoneStairs': True,
    'EmeraldOre': True,
    'EnderChest': True,
    'TripwireHook': False,
    'Tripwire': False,
    'EmeraldBlock': True,
    'SpruceStairs': True,
    'BirchStairs': True,
    'JungleStairs': True,
    'CommandBlock': True,
    'Beacon': True,
    'CobblestoneWall': True,
    'MossyCobblestoneWall': True,
    'FlowerPot': True,
    'PottedOakSapling': True,
    'PottedSpruceSapling': True,
    'PottedBirchSapling': True,
    'PottedJungleSapling': True,
    'PottedAcaciaSapling': True,
    'PottedDarkOakSapling': True,
    'PottedFern': True,
    'PottedDandelion': True,
    'PottedPoppy': True,
    'PottedBlueOrchid': True,
    'PottedAllium': True,
    'PottedAzureBluet': True,
    'PottedRedTulip': True,
    'PottedOrangeTulip': True,
    'PottedWhiteTulip': True,
    'PottedPinkTulip': True,
    'PottedOxeyeDaisy': True,
    'PottedCornflower': True,
    'PottedLilyOfTheValley': True,
    'PottedWitherRose': True,
    'PottedRedMushroom': True,
    'PottedBrownMushroom': True,
    'PottedDeadBush': True,
    'PottedCactus': True,
    'Carrots': False,
    'Potatoes': False,
    'OakButton': False,
    'SpruceButton': False,
    'BirchButton': False,
    'JungleButton': False,
    'AcaciaButton': False,
    'DarkOakButton': False,
    'SkeletonSkull': True,
    'SkeletonWallSkull': True,
    'WitherSkeletonSkull': True,
    'WitherSkeletonWallSkull': True,
    'ZombieHead': True,
    'ZombieWallHead': True,
    'PlayerHead': True,
    'PlayerWallHead': True,
    'CreeperHead': True,
    'CreeperWallHead': True,
    'DragonHead': True,
    'DragonWallHead': True,
    'Anvil': True,
    'ChippedAnvil': True,
    'DamagedAnvil': True,
    'TrappedChest': True,
    'LightWeightedPressurePlate': False,
    'HeavyWeightedPressurePlate': False,
    'Comparator': True,
    'DaylightDetector': True,
    'RedstoneBlock': True,
    'NetherQuartzOre': True,
    'Hopper': True,
    'QuartzBlock': True,
    'ChiseledQuartzBlock': True,
    'QuartzPillar': True,
    'QuartzStairs': True,
    'ActivatorRail': False,
    'Dropper': True,
    'WhiteTerracotta': True,
    'OrangeTerracotta': True,
    'MagentaTerracotta': True,
    'LightBlueTerracotta': True,
    'YellowTerracotta': True,
    'LimeTerracotta': True,
    'PinkTerracotta': True,
    'GrayTerracotta': True,
    'LightGrayTerracotta': True,
    'CyanTerracotta': True,
    'PurpleTerracotta': True,
    'BlueTerracotta': True,
    'BrownTerracotta': True,
    'GreenTerracotta': True,
    'RedTerracotta': True,
    'BlackTerracotta': True,
    'WhiteStainedGlassPane': True,
    'OrangeStainedGlassPane': True,
    'MagentaStainedGlassPane': True,
    'LightBlueStainedGlassPane': True,
    'YellowStainedGlassPane': True,
    'LimeStainedGlassPane': True,
    'PinkStainedGlassPane': True,
    'GrayStainedGlassPane': True,
    'LightGrayStainedGlassPane': True,
    'CyanStainedGlassPane': True,
    'PurpleStainedGlassPane': True,
    'BlueStainedGlassPane': True,
    'BrownStainedGlassPane': True,
    'GreenStainedGlassPane': True,
    'RedStainedGlassPane': True,
    'BlackStainedGlassPane': True,
    'AcaciaStairs': True,
    'DarkOakStairs': True,
    'SlimeBlock': True,
    'Barrier': True,
    'IronTrapdoor': True,
    'Prismarine': True,
    'PrismarineBricks': True,
    'DarkPrismarine': True,
    'PrismarineStairs': True,
    'PrismarineBrickStairs': True,
    'DarkPrismarineStairs': True,
    'PrismarineSlab': True,
    'PrismarineBrickSlab': True,
    'DarkPrismarineSlab': True,
    'SeaLantern': True,
    'HayBlock': True,
    'WhiteCarpet': True,
    'OrangeCarpet': True,
    'MagentaCarpet': True,
    'LightBlueCarpet': True,
    'YellowCarpet': True,
    'LimeCarpet': True,
    'PinkCarpet': True,
    'GrayCarpet': True,
    'LightGrayCarpet': True,
    'CyanCarpet': True,
    'PurpleCarpet': True,
    'BlueCarpet': True,
    'BrownCarpet': True,
    'GreenCarpet': True,
    'RedCarpet': True,
    'BlackCarpet': True,
    'Terracotta': True,
    'CoalBlock': True,
    'PackedIce': True,
    'Sunflower': False,
    'Lilac': False,
    'RoseBush': False,
    'Peony': False,
    'TallGrass': False,
    'LargeFern': False,
    'WhiteBanner': False,
    'OrangeBanner': False,
    'MagentaBanner': False,
    'LightBlueBanner': False,
    'YellowBanner': False,
    'LimeBanner': False,
    'PinkBanner': False,
    'GrayBanner': False,
    'LightGrayBanner': False,
    'CyanBanner': False,
    'PurpleBanner': False,
    'BlueBanner': False,
    'BrownBanner': False,
    'GreenBanner': False,
    'RedBanner': False,
    'BlackBanner': False,
    'WhiteWallBanner': False,
    'OrangeWallBanner': False,
    'MagentaWallBanner': False,
    'LightBlueWallBanner': False,
    'YellowWallBanner': False,
    'LimeWallBanner': False,
    'PinkWallBanner': False,
    'GrayWallBanner': False,
    'LightGrayWallBanner': False,
    'CyanWallBanner': False,
    'PurpleWallBanner': False,
    'BlueWallBanner': False,
    'BrownWallBanner': False,
    'GreenWallBanner': False,
    'RedWallBanner': False,
    'BlackWallBanner': False,
    'RedSandstone': True,
    'ChiseledRedSandstone': True,
    'CutRedSandstone': True,
    'RedSandstoneStairs': True,
    'OakSlab': True,
    'SpruceSlab': True,
    'BirchSlab': True,
    'JungleSlab': True,
    'AcaciaSlab': True,
    'DarkOakSlab': True,
    'StoneSlab': True,
    'SmoothStoneSlab': True,
    'SandstoneSlab': True,
    'CutSandstoneSlab': True,
    'PetrifiedOakSlab': True,
    'CobblestoneSlab': True,
    'BrickSlab': True,
    'StoneBrickSlab': True,
    'NetherBrickSlab': True,
    'QuartzSlab': True,
    'RedSandstoneSlab': True,
    'CutRedSandstoneSlab': True,
    'PurpurSlab': True,
    'SmoothStone': True,
    'SmoothSandstone': True,
    'SmoothQuartz': True,
    'SmoothRedSandstone': True,
    'SpruceFenceGate': True,
    'BirchFenceGate': True,
    'JungleFenceGate': True,
    'AcaciaFenceGate': True,
    'DarkOakFenceGate': True,
    'SpruceFence': True,
    'BirchFence': True,
    'JungleFence': True,
    'AcaciaFence': True,
    'DarkOakFence': True,
    'SpruceDoor': True,
    'BirchDoor': True,
    'JungleDoor': True,
    'AcaciaDoor': True,
    'DarkOakDoor': True,
    'EndRod': True,
    'ChorusPlant': True,
    'ChorusFlower': True,
    'PurpurBlock': True,
    'PurpurPillar': True,
    'PurpurStairs': True,
    'EndStoneBricks': True,
    'Beetroots': False,
    'GrassPath': True,
    'EndGateway': False,
    'RepeatingCommandBlock': True,
    'ChainCommandBlock': True,
    'FrostedIce': True,
    'MagmaBlock': True,
    'NetherWartBlock': True,
    'RedNetherBricks': True,
    'BoneBlock': True,
    'StructureVoid': False,
    'Observer': True,
    'ShulkerBox': True,
    'WhiteShulkerBox': True,
    'OrangeShulkerBox': True,
    'MagentaShulkerBox': True,
    'LightBlueShulkerBox': True,
    'YellowShulkerBox': True,
    'LimeShulkerBox': True,
    'PinkShulkerBox': True,
    'GrayShulkerBox': True,
    'LightGrayShulkerBox': True,
    'CyanShulkerBox': True,
    'PurpleShulkerBox': True,
    'BlueShulkerBox': True,
    'BrownShulkerBox': True,
    'GreenShulkerBox': True,
    'RedShulkerBox': True,
    'BlackShulkerBox': True,
    'WhiteGlazedTerracotta': True,
    'OrangeGlazedTerracotta': True,
    'MagentaGlazedTerracotta': True,
    'LightBlueGlazedTerracotta': True,
    'YellowGlazedTerracotta': True,
    'LimeGlazedTerracotta': True,
    'PinkGlazedTerracotta': True,
    'GrayGlazedTerracotta': True,
    'LightGrayGlazedTerracotta': True,
    'CyanGlazedTerracotta': True,
    'PurpleGlazedTerracotta': True,
    'BlueGlazedTerracotta': True,
    'BrownGlazedTerracotta': True,
    'GreenGlazedTerracotta': True,
    'RedGlazedTerracotta': True,
    'BlackGlazedTerracotta': True,
    'WhiteConcrete': True,
    'OrangeConcrete': True,
    'MagentaConcrete': True,
    'LightBlueConcrete': True,
    'YellowConcrete': True,
    'LimeConcrete': True,
    'PinkConcrete': True,
    'GrayConcrete': True,
    'LightGrayConcrete': True,
    'CyanConcrete': True,
    'PurpleConcrete': True,
    'BlueConcrete': True,
    'BrownConcrete': True,
    'GreenConcrete': True,
    'RedConcrete': True,
    'BlackConcrete': True,
    'WhiteConcretePowder': True,
    'OrangeConcretePowder': True,
    'MagentaConcretePowder': True,
    'LightBlueConcretePowder': True,
    'YellowConcretePowder': True,
    'LimeConcretePowder': True,
    'PinkConcretePowder': True,
    'GrayConcretePowder': True,
    'LightGrayConcretePowder': True,
    'CyanConcretePowder': True,
    'PurpleConcretePowder': True,
    'BlueConcretePowder': True,
    'BrownConcretePowder': True,
    'GreenConcretePowder': True,
    'RedConcretePowder': True,
    'BlackConcretePowder': True,
    'Kelp': False,
    'KelpPlant': False,
    'DriedKelpBlock': True,
    'TurtleEgg': True,
    'DeadTubeCoralBlock': True,
    'DeadBrainCoralBlock': True,
    'DeadBubbleCoralBlock': True,
    'DeadFireCoralBlock': True,
    'DeadHornCoralBlock': True,
    'TubeCoralBlock': True,
    'BrainCoralBlock': True,
    'BubbleCoralBlock': True,
    'FireCoralBlock': True,
    'HornCoralBlock': True,
    'DeadTubeCoral': False,
    'DeadBrainCoral': False,
    'DeadBubbleCoral': False,
    'DeadFireCoral': False,
    'DeadHornCoral': False,
    'TubeCoral': False,
    'BrainCoral': False,
    'BubbleCoral': False,
    'FireCoral': False,
    'HornCoral': False,
    'DeadTubeCoralFan': False,
    'DeadBrainCoralFan': False,
    'DeadBubbleCoralFan': False,
    'DeadFireCoralFan': False,
    'DeadHornCoralFan': False,
    'TubeCoralFan': False,
    'BrainCoralFan': False,
    'BubbleCoralFan': False,
    'FireCoralFan': False,
    'HornCoralFan': False,
    'DeadTubeCoralWallFan': False,
    'DeadBrainCoralWallFan': False,
    'DeadBubbleCoralWallFan': False,
    'DeadFireCoralWallFan': False,
    'DeadHornCoralWallFan': False,
    'TubeCoralWallFan': False,
    'BrainCoralWallFan': False,
    'BubbleCoralWallFan': False,
    'FireCoralWallFan': False,
    'HornCoralWallFan': False,
    'SeaPickle': True,
    'BlueIce': True,
    'Conduit': True,
    'BambooSapling': False,
    'Bamboo': True,
    'PottedBamboo': True,
    'VoidAir': False,
    'CaveAir': False,
    'BubbleColumn': False,
    'PolishedGraniteStairs': True,
    'SmoothRedSandstoneStairs': True,
    'MossyStoneBrickStairs': True,
    'PolishedDioriteStairs': True,
    'MossyCobblestoneStairs': True,
    'EndStoneBrickStairs': True,
    'StoneStairs': True,
    'SmoothSandstoneStairs': True,
    'SmoothQuartzStairs': True,
    'GraniteStairs': True,
    'AndesiteStairs': True,
    'RedNetherBrickStairs': True,
    'PolishedAndesiteStairs': True,
    'DioriteStairs': True,
    'PolishedGraniteSlab': True,
    'SmoothRedSandstoneSlab': True,
    'MossyStoneBrickSlab': True,
    'PolishedDioriteSlab': True,
    'MossyCobblestoneSlab': True,
    'EndStoneBrickSlab': True,
    'SmoothSandstoneSlab': True,
    'SmoothQuartzSlab': True,
    'GraniteSlab': True,
    'AndesiteSlab': True,
    'RedNetherBrickSlab': True,
    'PolishedAndesiteSlab': True,
    'DioriteSlab': True,
    'BrickWall': True,
    'PrismarineWall': True,
    'RedSandstoneWall': True,
    'MossyStoneBrickWall': True,
    'GraniteWall': True,
    'StoneBrickWall': True,
    'NetherBrickWall': True,
    'AndesiteWall': True,
    'RedNetherBrickWall': True,
    'SandstoneWall': True,
    'EndStoneBrickWall': True,
    'DioriteWall': True,
    'Scaffolding': True,
    'Loom': True,
    'Barrel': True,
    'Smoker': True,
    'BlastFurnace': True,
    'CartographyTable': True,
    'FletchingTable': True,
    'Grindstone': True,
    'Lectern': True,
    'SmithingTable': True,
    'Stonecutter': True,
    'Bell': True,
    'Lantern': True,
    'SoulLantern': True,
    'Campfire': True,
    'SoulCampfire': True,
    'SweetBerryBush': False,
    'WarpedStem': True,
    'StrippedWarpedStem': True,
    'WarpedHyphae': True,
    'StrippedWarpedHyphae': True,
    'WarpedNylium': True,
    'WarpedFungus': False,
    'WarpedWartBlock': True,
    'WarpedRoots': False,
    'NetherSprouts': False,
    'CrimsonStem': True,
    'StrippedCrimsonStem': True,
    'CrimsonHyphae': True,
    'StrippedCrimsonHyphae': True,
    'CrimsonNylium': True,
    'CrimsonFungus': False,
    'Shroomlight': True,
    'WeepingVines': False,
    'WeepingVinesPlant': False,
    'TwistingVines': False,
    'TwistingVinesPlant': False,
    'CrimsonRoots': False,
    'CrimsonPlanks': True,
    'WarpedPlanks': True,
    'CrimsonSlab': True,
    'WarpedSlab': True,
    'CrimsonPressurePlate': False,
    'WarpedPressurePlate': False,
    'CrimsonFence': True,
    'WarpedFence': True,
    'CrimsonTrapdoor': True,
    'WarpedTrapdoor': True,
    'CrimsonFenceGate': True,
    'WarpedFenceGate': True,
    'CrimsonStairs': True,
    'WarpedStairs': True,
    'CrimsonButton': False,
    'WarpedButton': False,
    'CrimsonDoor': True,
    'WarpedDoor': True,
    'CrimsonSign': False,
    'WarpedSign': False,
    'CrimsonWallSign': False,
    'WarpedWallSign': False,
    'StructureBlock': True,
    'Jigsaw': True,
    'Composter': True,
    'Target': True,
    'BeeNest': True,
    'Beehive': True,
    'HoneyBlock': True,
    'HoneycombBlock': True,
    'NetheriteBlock': True,
    'AncientDebris': True,
    'CryingObsidian': True,
    'RespawnAnchor': True,
    'PottedCrimsonFungus': True,
    'PottedWarpedFungus': True,
    'PottedCrimsonRoots': True,
    'PottedWarpedRoots': True,
    'Lodestone': True,
    'Blackstone': True,
    'BlackstoneStairs': True,
    'BlackstoneWall': True,
    'BlackstoneSlab': True,
    'PolishedBlackstone': True,
    'PolishedBlackstoneBricks': True,
    'CrackedPolishedBlackstoneBricks': True,
    'ChiseledPolishedBlackstone': True,
    'PolishedBlackstoneBrickSlab': True,
    'PolishedBlackstoneBrickStairs': True,
    'PolishedBlackstoneBrickWall': True,
    'GildedBlackstone': True,
    'PolishedBlackstoneStairs': True,
    'PolishedBlackstoneSlab': True,
    'PolishedBlackstonePressurePlate': False,
    'PolishedBlackstoneButton': False,
    'PolishedBlackstoneWall': True,
    'ChiseledNetherBricks': True,
    'CrackedNetherBricks': True,
    'QuartzBricks': True,
}

def to_pascal_case(st):
    result = st[0]
    for s in st[1:]:
        if s.capitalize() == s:
            result += f'_{s}'
        else:
            result += s
    return ''.join(result)


for bt in block_types:
    sol = solid[bt]

    if sol:
        print(f'    {bt},')

for bt in block_types:
    sol = solid[bt]

    if sol:
        print(f'const BLOCK_{to_pascal_case(bt).upper()}: BlockTypeInfo = BlockTypeInfo::new_opaque_mono_side("{to_pascal_case(bt).lower()}.png");')

for bt in block_types:
    sol = solid[bt]

    if sol:
        print(f'        BlockType::{bt} => Some(&BLOCK_{to_pascal_case(bt).upper()}),')
