river_noise: !noise
  fractal_octaves: 2
  fractal_gain: 2.0
  fractal_lacunarity: 1.1
  frequency: 0.04
  multiplier: 10.0

river_noise: !noise
  fractal_type: fbm
  fractal_octaves: 4
  fractal_gain: 1.0
  fractal_lacunarity: 1.0
  frequency: 0.005
  miltiplier: 4.0

stream_noise: !noise
  fractal_type: rigid_multi
  fractal_octaves: 4
  fractal_gain: 0.52
  fractal_lacunarity: 0.05
  frequency: 0.008
  miltiplier: 3.0
