
pub const DEFAULT_RESOURCES: &'static [&'static str] = &[
	"default://assets/block/dirt.png",
	"default://assets/block/grass_block_top.png",
	"default://assets/block/grass_block_side.png",
	"default://assets/block/grass_block_side_overlay.png",

    "default://assets/block/water_overlay.png",

	"default://assets/block/stone.png",
	"default://assets/block/smooth_stone.png",
    "default://assets/block/stone_bricks.png",
    "default://assets/block/cracked_stone_bricks.png",
    "default://assets/block/mossy_stone_bricks.png",

	"default://assets/block/gravel.png",
	"default://assets/block/coarse_dirt.png",
	"default://assets/block/bedrock.png",
	"default://assets/block/sand.png",
	"default://assets/block/amethyst_block.png",
	"default://assets/block/bookshelf.png",
	"default://assets/block/iron_block.png",

	"default://assets/block/sandstone.png",
	"default://assets/block/sandstone_bottom.png",
	"default://assets/block/sandstone_top.png",
	"default://assets/block/chiseled_sandstone.png",

	"default://assets/block/podzol_side.png",
	"default://assets/block/podzol_top.png",

    "default://assets/block/hay_block_top.png",
    "default://assets/block/hay_block_side.png",

    "default://assets/block/blackstone.png",
    "default://assets/block/polished_blackstone.png",
    "default://assets/block/andesite.png",
    "default://assets/block/deepslate.png",
    "default://assets/block/deepslate_bricks.png",
    "default://assets/block/cracked_deepslate_bricks.png",
    "default://assets/block/polished_deepslate.png",
    "default://assets/block/diorite.png",
    "default://assets/block/polished_diorite.png",
    "default://assets/block/granite.png",
    "default://assets/block/polished_granite.png",
    "default://assets/block/cobblestone.png",
    "default://assets/block/mossy_cobblestone.png",

	"default://assets/block/acacia_log_top.png",
	"default://assets/block/acacia_log.png",
    "default://assets/block/acacia_leaves.png",
	"default://assets/block/acacia_planks.png",

    "default://assets/block/birch_leaves.png",
    "default://assets/block/birch_log.png",
    "default://assets/block/birch_log_top.png",
    "default://assets/block/birch_planks.png",

    "default://assets/block/dark_oak_leaves.png",
    "default://assets/block/dark_oak_log.png",
    "default://assets/block/dark_oak_log_top.png",
    "default://assets/block/dark_oak_planks.png",

    "default://assets/block/jungle_leaves.png",
    "default://assets/block/jungle_log.png",
    "default://assets/block/jungle_log_top.png",
    "default://assets/block/jungle_planks.png",

    "default://assets/block/oak_leaves.png",
    "default://assets/block/oak_log.png",
    "default://assets/block/oak_log_top.png",
    "default://assets/block/oak_planks.png",

    "default://assets/block/spruce_leaves.png",
    "default://assets/block/spruce_log.png",
    "default://assets/block/spruce_log_top.png",
    "default://assets/block/spruce_planks.png",

    "default://assets/block/grass.png",
    "default://assets/block/allium.png",
    "default://assets/block/blue_orchid.png",
    "default://assets/block/cobweb.png",
    "default://assets/block/cornflower.png",
    "default://assets/block/dandelion.png",
    "default://assets/block/lily_of_the_valley.png",
    "default://assets/block/lilac_top.png",
    "default://assets/block/lilac_bottom.png",
    "default://assets/block/orange_tulip.png",
    "default://assets/block/oxeye_daisy.png",
    "default://assets/block/peony_bottom.png",
    "default://assets/block/peony_top.png",
    "default://assets/block/pink_tulip.png",
    "default://assets/block/poppy.png",
    "default://assets/block/red_tulip.png",
    "default://assets/block/rose_bush_bottom.png",
    "default://assets/block/rose_bush_top.png",
    "default://assets/block/white_tulip.png",
    "default://assets/block/tall_grass_bottom.png",
    "default://assets/block/tall_grass_top.png",

	"default://assets/models/generic/generic.glb",
	"default://assets/gui/textures/elements.png",

    "foliage://bush_small.glb",
    "foliage://flower_lupin.glb",
    "foliage://flower_lupin2.glb",
    "foliage://flower_orchid.glb",
    "foliage://flower_rose.glb",
    "foliage://flower_white.glb",
    "foliage://flower_white2.glb",
    "foliage://flower_yellow.glb",
    "foliage://flower_yellow2.glb",
    "foliage://flower_yellow3.glb",
    "foliage://grass1.glb",
    "foliage://grass2.glb",
    "foliage://grass3.glb",
    "foliage://grass4.glb",
    "foliage://ground_moss1.glb",
    "foliage://ground_moss2.glb",
    "foliage://ground_moss3.glb",
    "foliage://tall_grass1.glb",
    "foliage://tall_grass2.glb",
];
